spring.application.name=activitepratique2

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:activitie2Db
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false
#
## Keycloak OAuth2
#spring.security.oauth2.client.registration.keycloak.client-id=products-client
#spring.security.oauth2.client.registration.keycloak.client-secret=soGNllGqbCjcXFFmieGTBhl3OUCcXMj0
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8080/login/oauth2/code/keycloak
#spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8180/realms/products-realm